config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "recipes#index"
  resources :recipes do
    resources :ingredients
  end
  resource :ingredients

  get '/pantry', to: 'ingredients#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients

  def in_stock_str
    in_stock ? "Yes" : "No"
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true

  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients

  def in_stock
    ingredients.all?(&:in_stock)
  end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient

  def name
    ingredient.name
  end

  def in_stock
    ingredient.in_stock
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :get_recipe, only: [:show, :new, :create, :destroy]

  def index
    @ingredients = Ingredient.all
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    recipe_ingredient = RecipeIngredient.find(params[:recipe_id])
    recipe_ingredient.update(ingredient_amount_params)
    recipe_ingredient.save
    redirect_to edit_recipe_path(recipe_ingredient.recipe)
  end

  def new
    @ingredient = @recipe.ingredients.build
  end

  def create
    @ingredient = Ingredient.find_by(ingredient_params)

    if @ingredient.nil?
      logger.info "ingredient not found in pantry, creating, then adding to recipe"
      @ingredient = Ingredient.new ingredient_params
      @ingredient.in_stock = true
      @ingredient.save
    else
      logger.info "ingredient already in pantry, adding to recipe"
    end

    @recipe.ingredients << @ingredient
    ri = RecipeIngredient.find_by(recipe: @recipe, ingredient: @ingredient)
    ri.amount = params[:recipe_ingredient][:amount]
    ri.save

    redirect_to edit_recipe_path(@recipe)
  end

  def destroy
    ingredient = Ingredient.find(params[:id])
    @recipe.ingredients.delete(ingredient)
    redirect_to edit_recipe_path(@recipe)
  end

  private
  def ingredient_params
    params.require(:ingredient).permit(:name)
  end
  
  def ingredient_amount_params
    params.require(:recipe_ingredient).permit(:amount)
  end

  def get_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    logger.info "showing all recipes"
    with_ingredients = params[:with_ingredients]
    if !with_ingredients.nil?
      rec_ing = RecipeIngredient.where(ingredient: with_ingredients).group(:recipe)
      @recipes = rec_ing.map(&:recipe)
    else
      @recipes = Recipe.all
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update(recipe_params)
    @recipe.save
    redirect_to @recipe
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to @recipe
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def recipe_params
    params.require(:recipe).permit(:name, :instructions)
  end
end

app/controllers/shopping_controller.rb
class ShoppingController < ApplicationController
  def index
    recipe = params[:for_recipe] ? Recipe.find(params[:for_recipe]) : nil
    if recipe
      ingredients = recipe.ingredients.where(in_stock: false)
    else
      ingredients = Ingredient.where(in_stock: false)
    end
    render json: ingredients
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'current' : ''
    
    content_tag(:li, class: class_name) do
      link_to link_text, link_path
    end
  end
end

app/views/ingredients/index.html.erb
<h1>Pantry</h1>
<turbo-frame id="ingredients">
    <table style="width: 100%;">
        <!-- Table Header Row -->
        <tr>
            <th>Ingredient</th>
            <th>In Stock</th>
        </tr>
        <!-- Table body, one row per ingredient -->
        <% @ingredients.each do |ingredient| %>
            <tr id="ingredient_<%= ingredient.id %>">
                <td><%= ingredient.name %></td>
                <td>
                    <% if ingredient.in_stock %>
                        Yes
                    <% else %>
                        <span style="color: red"><strong>No</strong></span>
                    <% end %>
                </td>
                    
            </tr>
        <% end %>
    </table>
</turbo-frame>

app/views/ingredients/new.html.erb
<turbo-frame id="new_recipe">
    <li>
        <%= form_with model: [@recipe, @ingredient], class: "inline" do |form| %>
            <%= fields_for :recipe_ingredient do |recipe_ingredient| %>
                <%= recipe_ingredient.text_field :amount, placeholder: "Amount" %>
            <% end %>
            <%= form.text_field :name, placeholder: "Ingredient" %>
            <%= form.submit %>
        <% end %>
    </li>
</turbo-frame>

app/views/ingredients/show.html.erb
<h1><%= @ingredient.name %></h1>
<%= link_to :back, :back %>
<h2>In Stock: <%= @ingredient.in_stock_str %></h2>
<% unless @ingredient.recipes.empty? %>
    <h2>In Recipes</h2>
    <ul>
        <% @ingredient.recipes.each do |recipe| %>
            <li><%= link_to recipe.name, recipe %></li>
        <% end %>
    </ul>
<% end %>

app/views/layouts/_navbar.html.erb
<nav>
    <ul>
        <%= nav_link "Recipes", recipes_path %>
        <%= nav_link "Pantry", pantry_path %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pantry</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= render 'layouts/navbar' %>
      <div class="container">
          <%= yield %>
      </div>
  </body>
</html>

app/views/recipes/edit.html.erb
<h1><%= @recipe.name %></h1>
<div>
    <%= link_to "Back", @recipe %>
</div>
<h2>Ingredients</h2>
<turbo-frame id="ingredients">
    <ul>
        <% @recipe.recipe_ingredients.each do |ingredient| %>
            <li>
                <%= button_to "✘", recipe_ingredient_path(@recipe, ingredient.ingredient), method: :delete %>
                <%= form_with model: ingredient, class: "inline" do |form| %>
                    <%= form.text_field :amount %>
                    <%= form.submit "save" %>
                    <strong><%= ingredient.ingredient.name %></strong>
                <% end %>
            </li>
        <% end %>
        <li>
            <turbo-frame id="new_recipe">
                <a class="new"
                   href="<%= new_recipe_ingredient_path(@recipe) %>">
                    <i>Add ingredient</i>
                </a>
            </turbo-frame>
        </li>
    </ul>
</turbo-frame>

<h2>Instructions</h2>
<%= form_with model: @recipe do |form| %>
    <div>
        <%= form.text_area :instructions, size: "120x30" %>
    </div>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/recipes/index.html.erb
<div class="box">
    <h1>Recipes</h1>
    <h2><%= link_to "New Recipe", new_recipe_path %></h2>
</div>
<ul>
    <% @recipes.each do |recipe| %>
        <li>
            <%= link_to recipe.name, recipe %>
            <% unless recipe.in_stock %>
                <strong>Missing Ingredients</strong>
            <% end %>
            <%= link_to "Edit", edit_recipe_path(recipe) %>
        </li>
    <% end %>
</ul>

app/views/recipes/new.html.erb
<%= form_with model: @recipe do |form| %>
    <div>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
    </div>

    <div>
        <% @recipe.errors.full_messages_for(:name).each do |message| %>
            <div style="color: red"><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/recipes/show.html.erb
<h1>
    <%= @recipe.name %>
</h1>

<%= link_to "Back", recipes_path %>
<%= link_to "Edit", edit_recipe_path(@recipe) %>
<h2>Ingredients</h2>
<ul>
    <% @recipe.recipe_ingredients.each do |ingredient| %>
        <li>
            <i><%= ingredient.amount %></i>
            <strong><%= ingredient.name %></strong>
        </li>
    <% end %>
</ul>

<h2>Instructions</h2>
<div>
    <%= @recipe.instructions %>
</div>